CONFIG_ZMK_BLE=y
CONFIG_ZMK_KEYBOARD_NAME="andres keeb"
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y

# TEMPORARY: Remove these two lines after flashing once to clear stale BLE state
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=y
CONFIG_ZMK_SETTINGS_RESET_ON_START=y
