# Identity
CONFIG_USB_DEVICE_PRODUCT="keeb"

# Power Management
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Bluetooth Core
CONFIG_ZMK_BLE=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Split Settings
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Compatibility
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y

CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y